[package]
name = "stochasticsampling"
version = "0.1.0"
authors = ["fkoessel <fkoessel@uni-mainz.de>"]

[[bin]]
doc = false
name = "simulation"

[dependencies]
log = "0.3"
env_logger = "0.3"
rand = "0.3"
#pcg_rand = "0.7"
toml = "0.1"
rustc-serialize = "*"
mpi = { git = "https://github.com/bsteinb/rsmpi.git", tag = "0.4.0" }
ndarray = { git = "https://github.com/bluss/rust-ndarray", branch = "master" }

[dev-dependencies]
quickcheck = "*"

[workspace]
members = ["src/fftw3"]
