[package]
name = "stochasticsampling"
version = "0.2.3"
authors = ["fkoessel <fkoessel@uni-mainz.de>"]

[[bin]]
doc = false
name = "simulation"

[dependencies]
bincode = "0.6.0"
clap = { version = "~2.19.0", features = ["yaml"] }
env_logger = "0.3.5"
error-chain = "0.7.1"
fftw3 = { path = "crates/fftw3" }
log = "0.3.6"
mpi = { git = "https://github.com/bsteinb/rsmpi.git", tag = "0.4.0" }
ndarray = { version = "0.7.1", features = ["serde"] }
pcg_rand = { path = "crates/external/pcg_rand"}
pbr = "1.0.0-alpha.1"
rand = "0.3.15"
serde = "0.8.19"
serde_cbor = "0.4.0"
serde_derive = "0.8.19"
time = "0.1.35"
toml = { version = "0.2.1", default-features = false, features = ["serde"] }

[dev-dependencies]
quickcheck = "0.3"

[workspace]
members = ["crates/fftw3"]

[profile.release]
lto = true
