[package]
name = "stochasticsampling"
version = "0.1.0"
authors = ["fkoessel <fkoessel@uni-mainz.de>"]

[[bin]]
doc = false
name = "simulation"

[dependencies]
env_logger = "0.3"
fftw3 = { path = "crates/fftw3" }
log = "0.3"
mpi = { git = "https://github.com/bsteinb/rsmpi.git", tag = "0.4.0" }
ndarray = { version = "0.6", features = ["serde"] }
pcg_rand = { path = "crates/external/pcg_rand"}
rand = "0.3"
serde = "0.8.9"
serde_derive = "0.8.9"
serde_cbor = "0.4"
toml = { version = "0.2", default-features = false, features = ["serde"] }
time = "0.1"

[dev-dependencies]
quickcheck = "*"

[workspace]
members = ["crates/fftw3"]
