[package]
name = "stochasticsampling"
version = "0.3.1"
authors = ["fkoessel <fkoessel@uni-mainz.de>"]
build = "build.rs"

[[bin]]
doc = false
name = "simulation"
path = "src/main.rs"

[dependencies]
bincode = "0.8.0"
clap = { version = "2.25.1", features = ["yaml"] }
colored = "1.5.2"
env_logger = "0.4.2"
error-chain = "0.10.0"
fftw3 = { path = "crates/fftw3" }
log = "0.3.6"
ndarray = { version = "0.10.0", features = ["serde-1"] }
ndarray-parallel = "0.5.0"
num = "0.1.40"
pbr = "1.0.0"
pcg_rand = { path = "crates/external/pcg_rand"}
quaternion = "0.3.0"
rand = "0.3.15"
rayon = "0.8.2"
# rustfft = "2.0.0"
serde = "1.0.10"
serde_cbor = "0.6.1"
serde_derive = "1.0.10"
time = "0.1.35"
toml = { version = "0.4.2", default-features = false, features = ["serde"] }

[dev-dependencies]
quickcheck = "0.4"
ndarray-rand = "0.6.0"

[build-dependencies]
vergen = "0.1.1"

[workspace]
members = ["crates/fftw3"]

[profile.release]
lto = true
debug = false

[profile.bench]
lto = true
debug = true
opt-level = 3
