[package]
name = "stochasticsampling"
version = "0.2.28"
authors = ["fkoessel <fkoessel@uni-mainz.de>"]
build = false #"build.rs"

[[bin]]
doc = false
name = "simulation"

[dependencies]
bincode = "0.7.0"
clap = { version = "2.21.2", features = ["yaml"] }
colored = "1.4.1"
env_logger = "0.4.2"
error-chain = "0.10.0"
fftw3 = { path = "crates/fftw3" }
log = "0.3.6"
ndarray = { version = "0.9.0", features = ["serde"] }
pbr = { git = "https://github.com/a8m/pb.git", rev = "e6e1fe6e4aa4e99c4594aa4943a42e91cfb41f90" }
pcg_rand = { path = "crates/external/pcg_rand"}
rand = "0.3.15"
rayon = "0.7.0"
serde = "0.9.11"
serde_cbor = "0.5.2"
serde_derive = "0.9.11"
time = "0.1.35"
toml = { version = "0.3.1", default-features = false, features = ["serde"] }

[dev-dependencies]
quickcheck = "0.4"
ndarray-rand = "0.5.0"

[workspace]
members = ["crates/fftw3"]

[profile.release]
lto = true
debug = false
