[package]
name = "stochasticsampling"
version = "1.2.0"
authors = ["fkoessel <fkoessel@uni-mainz.de>"]
build = "build.rs"

[[bin]]
name = "simulation"
path = "src/bin/main.rs"

[dependencies]
bincode = "1.0.0"
clap = { version = "2.30.0", features = ["yaml"] }
colored = "1.5.2"
env_logger = "0.4.2"
error-chain = "0.11.0"
fftw3 = { path = "crates/fftw3" }
itertools = "0.7"
log = "0.3.6"
ndarray = { version = "0.11.0", features = ["serde-1"] }
ndarray-parallel = "0.8.0"
num-complex = "0.1"
pbr = "1.0.0"
pcg_rand = { path = "crates/external/pcg_rand" }
quaternion = "0.3.0"
rand = "0.3.15"
rayon = "1.0.0"
rmp-serde = "0.13.6"
# rustfft = "2.0.0"
rust-lzma = { path = "crates/external/rust-lzma" }
serde = "1.0.10"
serde_cbor = "0.8.2"
serde_derive = "1.0.10"
time = "0.1.35"
toml = { version = "0.4.2"}
extprim = "1.4.0"
#derive_more = "0.10.0"

[dev-dependencies]
quickcheck = "0.4"
ndarray-rand = "0.6.0"

[build-dependencies]
vergen = "0.1.1"

[workspace]
members = ["crates/fftw3", "crates/external/rust-lzma"]

[profile.release]
opt-level = 3
lto = false
debug = false
codegen-units = 1
incremental = false

[profile.bench]
lto = true
debug = true
opt-level = 3
codegen-units = 1
incremental = false
