[package]
name = "stochasticsampling"
version = "0.1.0"
authors = ["fkoessel <fkoessel@uni-mainz.de>"]

[[bin]]
doc = false
name = "simulation"

[dependencies]
rand = "0.3"
toml = "0.1"
serde = "*"
rustc-serialize = "*"
mpi = { git = "https://github.com/bsteinb/rsmpi.git", tag = "0.4.0" }

[dev-dependencies]
quickcheck = "*"
quickcheck_macros = "*"
