[package]
name = "stochasticsampling"
version = "0.2.18"
authors = ["fkoessel <fkoessel@uni-mainz.de>"]
build = false #"build.rs"

[[bin]]
doc = false
name = "simulation"

[dependencies]
bincode = "1.0.0-alpha5"
clap = { version = "~2.19.0", features = ["yaml"] }
env_logger = "0.3.5"
error-chain = "0.7.1"
fftw3 = { path = "crates/fftw3" }
log = "0.3.6"
ndarray = { version = "0.8.0", features = ["serde"] }
pcg_rand = { path = "crates/external/pcg_rand"}
pbr = { path = "crates/external/pb"}
rand = "0.3.15"
rayon = "0.6.0"
serde = "0.9.11"
serde_cbor = "0.5.2"
serde_derive = "0.9.11"
time = "0.1.35"
toml = { version = "0.3.1", default-features = false, features = ["serde"] }

[dev-dependencies]
quickcheck = "0.3"
ieee754 = "0.1"

[workspace]
members = ["crates/fftw3"]

[profile.release]
lto = true
#debug = true
