[package]
name = "fftw3"
version = "0.4.0"
authors = ["fkoessel <fkoessel@uni-mainz.de>"]

[features]
default = []
fftw-threaded = []
fftw-static = []
single = []


[dependencies]
ndarray = "0.12.0"
num-complex = "0.2"

[dev-dependencies]
quickcheck = "*"
